name: Clizio Guedes
description: Sem Álibi :D
meta_description: "Dê uma olhada"

markdown: kramdown
highlighter: rouge
logo: false
paginate: 15
baseurl: /
domain_name: 'https://clizioguedes.github.io'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://clizioguedes.github.io/'
author:         'Clizio Guedes'
