name: Clizio Guedes
description: Técnologo em Sistemas para Internet (Em Formação)
meta_description: "Meu novo Jekyll Site, Vou falar sobre tudo"

markdown: kramdown
highlighter: pygments
logo: false
paginate: 15
baseurl: /
domain_name: 'http://yourblog-domain.com'
google_analytics: 'UA-XXXXXXXX-X'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url:            'https://clizioguedes.github.io/'
author:         'Clizio Guedes'
